domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaygroup/TabShowConditionValidatorImplTest.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/SpreadsheetValidationErrorMessageCreatorTest.java
NOTE the branch number refers to the first story 1591 under 1831. It encompasses the entire logic needed for 1831. It was thought the whole logic would be split across 2 PRs but was easier to keep it under one.
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-1831
https://tools.hmcts.net/jira/browse/RDM-1591
https://tools.hmcts.net/jira/browse/RDM-1964
Change description
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> RDM-1831 Hide and show condition for a tab and tab field on a case view

application/src/main/resources/application.properties
Register `ccd_admin` as an authorised service for accessing Definition Store.
https://tools.hmcts.net/jira/browse/RDM-1944
Add `ccd_admin` to the list of authorised services allowed to access Definition Store.
```
[ ] Yes
[x] No
```
=> RDM-1944: Enable Case Admin Web application access to Definition Store API

infrastructure/main.tf, infrastructure/variables.tf
Declare `DEFINITION_STORE_S2S_AUTHORISED_SERVICES` environment variable explicitly, as this is required on the Azure platform (which does not use the default values defined in `application.properties`).
None.
Fixes a problem in the CNP `Demo` environment, where Case Definition Store was refusing access by Case Admin Web application because no authorised services were defined (due to the missing environment variable).
This change has already been tested manually by adding the missing environment variable via the Azure Portal and confirming that Case Admin Web is now able to access Case Definition Store.
```
[ ] Yes
[x] No
```
=> Add explicit declaration of environment variable for authorised services

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionController.java
Endpoint now required by Case Admin Web application, thus removing the "deprecated" marking.
https://tools.hmcts.net/jira/browse/RDM-2404
Removal of the "deprecated" marking against the `dataCaseTypeIdGet()` method (`GET /data/case-type/{id}` endpoint) in `CaseDefinitionController`. This change has been approved by @vlaurin.
```
[ ] Yes
[x] No
```
=> RDM-2404: Remove "deprecated" marking for /data/case-type/{id} endpoint

dependency-check-suppressions.xml
This CVE relates to Ethereum but is brought in by Codacy so does not
impact production.
https://tools.hmcts.net/jira/browse/RDM-2831
```
[ ] Yes
[x] No
```
=> Supress CVE-2018-13661 in codacy dependency

build.gradle
https://tools.hmcts.net/jira/browse/RDM-2619
I believe the logic is that when one timesout we'll try the other. So at
least there is a fallback to one that should work
```
[ ] Yes
[ ] No
```
=> Bintray: add mavenCentral to combat jcenter timeouts

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeLiteEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventLiteEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseEventLite.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/CaseTypeLite.java
https://tools.hmcts.net/jira/browse/RDM-2903
Added Case Event Lite object for returning the Events of a Case Type on GET /jurisdictions query. Also added pre_states to let the FE decide if the event is a "Create Event"
```
[ ] Yes
[X] No
```
=> RDM-2903 Make retrieval of Case Types faster in Create Case filters

repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-2918.xml
New database table for storing draft Case Definitions.
https://tools.hmcts.net/jira/browse/RDM-2918.
Liquibase changelog for creating new `definition_designer` table, for working with draft Definitions.
```
[ ] Yes
[x] No
```
=> [PREVIEW] RDM-2918: Database table definition for "definition_designer" table

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/exception/FileStorageException.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/AzureBlobStorageClient.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/RestResponseEntityExceptionHandler.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/DateTimeStringGenerator.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/azurestorage/service/AzureBlobStorageClientTest.java
https://tools.hmcts.net/jira/browse/RDM-3105.
Prefix filenames with the current date/time in UTC, in the format `yyyyMMddHHmmss`, to allow multiple, non-overwriting uploads of the same Definition file.
```
[ ] Yes
[x] No
```
=> RDM-3105: Prefix Definition filenames with timestamp upon Azure Storage upload

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/MultipleControllersEndpointIT.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/UserRoleModelMapper.java
Due to latest changes the user-role creation API has been broken due to null constraint in newly introduced `role` table. 
Now we use the role name submitted via API in both role reference and role name.
Also added a test for user-role creation...
https://tools.hmcts.net/jira/browse/RDM-3193
```
[ ] Yes
[X] No
```
=> RDM-3193 Error while calling create-user-role endpoint

dependency-check-suppressions.xml
"Untrusted search path vulnerability in PostgreSQL before 7.3.19, 7.4.x
before 7.4.17, 8.0.x before 8.0.13, 8.1.x before 8.1.9, and 8.2.x before
8.2.4 allows remote authenticated users, when permitted to call a
SECURITY DEFINER function, to gain the privileges of the function owner,
related to "search_path settings.".
The versions of PostgreSQL are too old we're on at least 9.6 on Azure.
https://tools.hmcts.net/jira/browse/RDM-3215
```
[ ] Yes
[x] No
```
=> Suppress CVE-2007-2138 only applies to old PotgreSQL versions

aat/build.gradle, app-insights/build.gradle, application/build.gradle, domain/build.gradle, elastic-search-support/build.gradle, excel-importer/build.gradle, integration-tests/build.gradle, repository/build.gradle, rest-api/build.gradle
This fixes the slow stashing and unstashing in the pipeline with this application,
it also saves lots of disk space on my machine for extra bonus points.
Prior to this change this is the size of all the jars built by this application:
```
$ find . -type f -name *.jar  -exec du -h {} \;
96M	./repository/build/libs/definition-store-repository-1.2.0-SNAPSHOT.jar
1.4G	./integration-tests/build/libs/integration-tests-1.2.0-SNAPSHOT.jar
624M	./excel-importer/build/libs/definition-store-excel-importer-1.2.0-SNAPSHOT.jar
56K	./gradle/wrapper/gradle-wrapper.jar
80M	./aat/build/libs/aat-1.2.0-SNAPSHOT.jar
244K	./aat/build/tmp/expandedArchives/org.jacoco.agent-0.8.0.jar_0a1ac833cae91eb2e2152073ffb36feb/jacocoagent.jar
62M	./app-insights/build/libs/app-insights-1.2.0-SNAPSHOT.jar
176M …
```
=> [PREVIEW] Fix slow pipeline

hub.Dockerfile
N/A
Fix version of Gradle to 4.10 to allow docker images to build
```
[ ] Yes
[x] No
```
=> fix gradle version in Docker hub

build.gradle, dependency-check-suppressions.xml
…rod dependency.
Temporarily suppress CVE-2019-7722 pmd vulnerabilities. This is non prod dependency.
```
[ ] Yes
[x] No
```
=> upgraded pmd tool version to 6.11.0 (CVE-2019-7722)

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-4344.
Add authorised roles (currently only `ccd-import`) for each of the actions available in CCD Admin Web.
```
[ ] Yes
[x] No
```
=> RDM-4344: Terraform configuration for CCD Admin Web role-based authorisation

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/CaseTypeServiceImpl.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationError.java
On the new ITHC env we noticed that for some reason sometimes the import validation errors are not returned to the UI and are not logged. This makes it difficult to understand what the issue is because the import just fails silently. 
This quick PR adds logging of validation errors 
```
2019-05-29T14:24:13.243 INFO  [http-nio-1732-exec-9] u.g.h.c.d.s.d.service.casetype.CaseTypeServiceImpl validationError: Invalid UserRole for case type 'AAT_PRIVATE', case state 'TODO'
2019-05-29T14:24:13.243 INFO  [http-nio-1732-exec-9] u.g.h.c.d.s.d.service.casetype.CaseTypeServiceImpl validationError: Invalid UserRole for case type 'AAT_PRIVATE', case state 'TODO'
```
```
[ ] Yes
[ x] No
```
=> Log import validation errors

infrastructure/perftest.tfvars, infrastructure/prod.tfvars
It looks like we scaled up the def store db on AAT but not on Prod. Scaling up on Prod and PerfTest as well
```
[ ] Yes
[ x] No
```
=> scale up db on prod and perftest to align to aat

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java
https://tools.hmcts.net/jira/browse/RDM-5242
Adding a dot  character when filtering override possibilities to avoid a bug when names have similar beginning.
```
[ ] Yes
[ X] No
```
=> RDM-5242 Overrides fix when the fields in one event have similar prefix

Jenkinsfile_CNP, application/src/main/resources/bootstrap.yaml, infrastructure/main.tf, infrastructure/outputs.tf
hmcts/cnp-jenkins-library#533 changed to using the component for looking up the vault prefix, it was expected that all teams were doing this, inside of your own vault there is no need to prefix the secret with the product.
```
[ ] Yes
[x ] No
```
=> RDM-5730-Fix PF team changes to infra and jenkinsfile

repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupEntity.java, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6336.xml
https://tools.hmcts.net/jira/browse/RDM-6336
This fixes an N+1 query loading DisplayGroupCaseFieldEntity from DisplayGroupEntity, and improves display group loading performance by indexing case_type_id in the display_group table.
```
[ ] Yes
[x] No
```
=> Performance improvements for /display/tab-structure/{id}

charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/requirements.yaml
java chart updated to latest version 2.15.0 to enable bulk-scanning
bulk-scanning is currently blocked because of a clash in the tpl in an old version of chart-java, this was fixed in ~2.10
```
[ ] Yes
[ ] No
```
=> RDM-6596-bumped java chart version

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionController.java, rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/CaseDefinitionControllerTest.java
https://tools.hmcts.net/jira/browse/RDM-6603?filter=-3
This endpoint is frequently called with a list of IDs to retrieve details of specific jurisdictions.
This line would load the requested jurisdictions, then also load every jurisdiction only to throw them away:
`return idsOptional.map(ids -> jurisdictionService.getAll(ids)).orElse(jurisdictionService.getAll());`
Optional.orElse is not lazily evaluated - it is just a java method chain:
```
[ ] Yes
[x] No
```
=> Fix duplicate query on /findJurisdictions

Jenkinsfile_CNP, aat/src/aat/resources/features/F-080/S-080.1.td.json, build.gradle
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-9522
Change description
Use latest version of befta-fw
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
=> RDM-9522 - Use befta-fw release providing callback url substitution

charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.yaml
https://tools.hmcts.net/jira/browse/RDM-10386
Flaky DefStore pipeline: investigate intermittent max_connections issue on AAT
```
[ ] Yes
[X] No
```
=> RDM-10386 updated DEFINITION_STORE_DB_MAX_POOL_SIZE to 25

application/src/main/resources/application.properties, build.gradle
https://tools.hmcts.net/jira/browse/RDM-10879
When changing from develop to master, we have had migrations that are ahead and this was causing the error and preventing the service start. This property disables the check.
```
[ ] Yes
[x ] No
```
=> RDM-10879 Set flyway.ignoreMissingMigrations to true.

build.gradle
https://tools.hmcts.net/jira/browse/RDM-12168
bump up dependencies to resolve CVE-2021-29425
```
[ ] Yes
[X] No
```
=> RDM-12168 CVE-2021-29425 - bump up dependencies to resolve CVE

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/CaseTypeTest.java
Disable shouldReturnCaseTypesWithJurisdictionFilter test due to performance failure
```
[ ] Yes
[x] No
```
=> Disable test due to perfomance fail

build.gradle, dependency-check-suppressions.xml
Override transitive dependency on Apache Commons Compress due to CVE-2021-35515, CVE-2021-35516, CVE-2021-35517 & CVE-2021-36090
```
[ ] Yes
[x] No
```
=> Override transitive dependency commons-compress

aat/.gitignore, aat/build.gradle, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreBeftaMain.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreBeftaRunner.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/elasticsearch/ElasticsearchImportDefinitionTest.java, aat/src/aat/resources/features/F-089/S-089.1.td.json, aat/src/aat/resources/features/F-090/S-090.2.td.json, aat/src/aat/resources/features/F-092 Conditional Event Post State/S-092.7.td.json, aat/src/aat/resources/features/F-093/S-600.1.td.json, aat/src/aat/resources/features/F-095 Event Enabling Condition/S-095.2.td.json, aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1.td.json, aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12.td.json, aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.3.td.json, aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.5.td.json, aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/S-098.1.td.json, aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/S-098.2.td.json, build.gradle
[RDM-12754](https://tools.hmcts.net/jira/browse/RDM-12754) _"Fix: Definition Store FTAs import raw BEFTA definition files with invalid callbacks"_
For happy path import tests use the generated definition files so the callback URLs are valid and correct for the given environment.
NB: This is a rebase of the branch used in #1064 against master branch.
```
[ ] Yes
[ ] No
```
=> RDM-12754 Fix: Definition Store FTAs import raw BEFTA definition files with invalid callbacks

aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/S-099.1.td.json, aat/src/aat/resources/features/F-100 SearchCriteria (GlobalSearch)/S-100.1.td.json
https://tools.hmcts.net/jira/browse/RDM-12800
Positive response functional tests that import valid definition files from ccd-test-definitions should use the new local path to the generated copy rather than load direct from the usual resource file location:  i.e. use the generated environment specific excel file rather than the raw excel file from ccd-test-definitions which contains the templated callback URLs which are invalid when not processed by BEFTA-FW.
```
[ ] Yes
[ ] No
```
=> RDM-12800 -  use the new local path to the generated copy of definition file

build.gradle, dependency-check-suppressions.xml
CCD-2113 (https://tools.hmcts.net/jira/browse/CCD-2113)
- Updated build.gradle. Set value of tomcatVersion property to 9.0.54 to resolve CVE-2021-42340.
- Removed suppression of CVE-2021-42340 from dependency-check-suppressions.xml.
```
[ ] Yes
[x] No
```
=> CCD-2113: Address CVE-2021-42340

build.gradle, dependency-check-suppressions.xml
CCD-2138 (https://tools.hmcts.net/jira/browse/CCD-2138)
- Updated build.gradle.  Set value of override of spring-framework.version property to 5.3.12 to address CVE-2021-22096.
- Removed temporary suppression of CVE-2021-22096 from dependency-check-suppressions.xml
```
[ ] Yes
[x] No
```
=> CCD-2138: Address CVE-2021-22096

dependency-check-suppressions.xml
CCD-2132 (https://tools.hmcts.net/jira/browse/CCD-2132)
- Removed temporary suppression of CVE-2021-22147 from dependency-check-suppressions.xml as CVE does not show up in output from gradle dependency check.  This may be because it only affects versions 7.11.0 to 7.13.4 (see https://discuss.elastic.co/t/elastic-stack-7-14-0-security-update/280344) rather than all versions prior to 7.14.0 (as reported at https://nvd.nist.gov/vuln/detail/CVE-2021-22147).
```
[ ] Yes
[x] No
```
=> CCD-2132: Remove suppression of CVE-2021-22147

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2231
Changed suppression dates from 2021-12-25 to 2022-01-25
```
[ ] Yes
[X] No
```
=> CCD-2231-update-cve-suppression-dates-dec-2021

charts/ccd-definition-store-api/values.preview.template.yaml, elastic-search-support/src/main/resources/globalSearchCasesMapping.json
[RDM-13127](https://tools.hmcts.net/jira/browse/RDM-13127) _"Access Control - CaseAccessCategory not working for the Global Search endpoint"_
Adjust how the CaseAccessCategory field is indexed in GlobalSearch so it uses the same analyzer config as the case type indexes.
> **NB: This release will require the GlobalSearch index to be deleted and recreated.**
> NB: This branch is required by: hmcts/ccd-data-store-api#1889
```
[ ] Yes
[ ] No
```
=> RDM-13127 adjust CaseAccessCategory in GS index

aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.8.td.json, aat/src/aat/resources/features/F-103 New DefaultValue Column/S-103.1.td.json, build.gradle, charts/ccd-definition-store-api/Chart.yaml
FT patch for tests to pass with the new def file [7.14.1](https://github.com/hmcts/ccd-test-definitions/releases/tag/7.14.1)
```
[ ] Yes
[X] No
```
=> PR to fix def-store tests with new def-file

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/CCD-2533
Fix Flaky Functional Tests in Definition Store by rescheduling the cron at 21:30 pm not to interfere the running tests and corrupt the data.
```
[ ] Yes
[x ] No
```
=> ccd-2533: Fix Flaky Functional Tests in Definition Store

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3100
A flaw was discovered in Elasticsearch 7.17.0’s upgrade assistant, in which upgrading from version 6.x to 7.x would disable the in-built protections on the security index, allowing authenticated users with “*” index permissions access to this index.
Upgraded to 7.17.1
```
[ ] Yes
[ x] No
```
=> CVE-2022-23708:ccd-definition-store-api

dependency-check-suppressions.xml
The package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via the writeReplace() method in internal classes, which may lead to DoS attacks.
CWE-502 Deserialization of Untrusted Data
```
[ ] Yes
[ x] No
```
=> CVE-2022-25647: suppression changes

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3099
1. Updated spring-framework.version t0 5.3.19
2. Remove suppression for CVE-2022-22968
```
[ ] Yes
[X] No
```
=> CCD-3099: Updated spring-framework.version to 5.3.19

aat/src/aat/resources/features/F-102 - TTL Base Complex Type/S-102.2.td.json, build.gradle, charts/ccd-definition-store-api/values.preview.template.yaml
[RDM-13140](https://tools.hmcts.net/jira/browse/RDM-13140) _"getLinkedCases API - retrieve case links from database and return response payload"_
Build against the next `ccd-test-definitions` pre-release, see hmcts/ccd-test-definitions#47.
```
[ ] Yes
[x] No
```
=> RDM-13140 test definition release for getLinkedCases API

application/build.gradle, build.gradle, dependency-check-suppressions.xml, integration-tests/build.gradle
https://tools.hmcts.net/jira/browse/CCD-2919
Upgrading to version postgresql:42.3.2.
https://nvd.nist.gov/vuln/detail/CVE-2022-21724
A security hole was found in the jdbc driver for postgresql database while doing security research
```
[ ] Yes
[ X] No
```
=> CVE-2022-21724 ccd-definition-store fix

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3440
False positive.   CVE-2022-33915 (cpe;2.3;a;apache;log4j) only impacts AWS Log4j hotpatch , and not general Log4j build.   See Jira ticket.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-3440: CVE-2022-33915 ccd-definition-store-api

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/CCD-3539
https://tools.hmcts.net/jira/browse/CCD-3574
CCD-3539: Stop running Nightly builds on weekends
CCD-3574: Remove FTs from nightly pipeline build
```
[ ] Yes
[X] No
```
=> CCD-3539-CCD-3574: Stop running Nightly builds on weekends, Removal of FTs

dependency-check-suppressions.xml
CCD-3604 (https://tools.hmcts.net/jira/browse/CCD-3604)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```
=> CCD-3604: Temporarily suppress CVE-2022-31197

application/build.gradle, build.gradle, dependency-check-suppressions.xml, integration-tests/build.gradle
https://tools.hmcts.net/jira/browse/CCD-3604
CCD-3604: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression
```
[ ] Yes
[X] No
```
=> CCD-3604: CVE-2022-31197 - Upgraded org.postgresql to 42.4.1 and removed temp suppression

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3429
CVE-2022-34305 tomcat upgrade 9.0.65
```
[ ] Yes
[ x] No
```
=> CCD-3429 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed

excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseStateParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationComplexTypeParser.java
https://tools.hmcts.net/jira/browse/CCD-3657
Stop Parser from grouping the same set of items on each loop. Items are now retrieved once.
```
[ ] Yes
[ x] No
```
=> Fix Parser performance issue

dependency-check-suppressions.xml
CCD-3776 (https://tools.hmcts.net/jira/browse/CCD-3776)
Updated suppressions file to temporarily suppress CVE-2022-42003 and CVE-2022-42004 pending fix.
```
[ ] Yes
[x] No
```
=> CCD-3776: Suppress CVE-2022-42003 and CVE-2022-42004

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4210
CVE-2022-45143 - upgrade Tomcat to 9.0.69
```
[ ] Yes
[ x] No
```
=> CCD-4210 CVE-2022-45143 - upgrade Tomcat to 9.0.69

.github/workflows/swagger.yml, README.md
https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : replaced reform-api-docs to cnp-api-docs
```
[ ] Yes
[X] No
```
=> CCD-4476 : replaced reform-api-docs to cnp-api-docs

aat/src/aat/resources/features/F-109 AccessTypeRoles/F-109.feature, aat/src/aat/resources/features/F-109 AccessTypeRoles/F-109_Definition_Import_Test_Base_data.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.10.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.11.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.12.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.13.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.14.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.15.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.16.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.17.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.18.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.2.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.22.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.23.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.3.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.4.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.5.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.6.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.7.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.8.td.json, aat/src/aat/resources/features/F-109 AccessTypeRoles/S-109.9.td.json, build.gradle
=> GA-3 Defintion import validations for new Tab AccessTypeRoles - BEFTA Tests

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5468
bumped postgresql to v42.5.5
```
[ ] Yes
[X] No
```
=> CCD-5468: bumped postgresql to v42.5.5

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5472
Fix CVE-2024-25710 bumped commons-compress to 1.26.0
```
[ ] Yes
[X] No
```
=> CCD-5472: Fix CVE-2024-25710 bumped commons-compress to 1.26.0

Jenkinsfile_CNP, build.gradle
=> Pipeline fix: Use beftaFw Version 9.2.0 and definitionStoreDevelopPr set to pr-575

aat/src/aat/resources/features/F-080/F-080.feature, aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/F-110.feature
https://tools.hmcts.net/jira/browse/CCD-6078
Master build has been failing consistently on specific FTs. On investigation the root cause seems to be related to the data that is stored in the common ccd-definition-store aat DB. Some repos/pipelines are still utilising an older version of ccd-test-definitions which on commit to the DB causes those repos with latest test-definitions to fail on FT. Suppressing the failing FTs until all repos are on latest ccd-test-definitions and befta-fw. 
```
[ ] Yes
[X] No
```
=> CCD-6078 : marked failing FTs with ignore

build.gradle
NA
9.2.3 is not available in Az Artifacts, bumped to 9.2.4
```
[ ] Yes
[X] No
```
=> bump befta-fw to 9.2.4
