.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
RDM-1950 Introduce travis to open source code
```
[ ] Yes
[x] No
```
=> RDM-1950 Introduce travis to open source code

infrastructure/aat.tfvars
N/A
Use preprod config for AAT
```
[ ] Yes
[x] No
```
=> CNP: Use preprod config for AAT

build.gradle, dependency-check-suppressions.xml
RDM-2012
Add dependency check
```
[x] Yes
[ ] No
```
=> RDM-2012 Add dependency check

Jenkinsfile_CNP, aat/build.gradle, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/AATHelper.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/BaseTest.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/S2SHelper.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/IdamApi.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/IdamHelper.java, build.gradle, dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/variables.tf
N/A
Add vault for functional tests
```
[ ] Yes
[x] No
```
=> Add vault for functional tests

Dockerfile, docker-compose.yml, hub.Dockerfile
RDM-2048
Add Docker image
```
[x] Yes
[ ] No
```
=> RDM-2048 Add Docker image

infrastructure/aat.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Disabled NL DB
Enable UK DB
```
[ ] Yes
[x] No
```
=> Switch on UK DB in AAT

dependency-check-suppressions.xml
=> RDM-2055 Add CVE to exception list.

infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
:warning: To be merged as part of release https://tools.hmcts.net/confluence/display/RSTR/CHG0032439+-+CCD+db+Migration+to+UK
```
[x] Yes
[ ] No
```
=> Do not merge: RDM-2173: Switch prod DB to UK South

application/src/main/resources/application.properties
N/A
Allow liquibase to be disabled by using property ENABLE_DB_MIGRATE
```
[ ] Yes
[x] No
```
=> Consume ENABLE_DB_MIGRATE property

infrastructure/demo.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Switch demo DBs to UK South
```
[ ] Yes
[x] No
```
=> Switch demo DBs to UK South

Jenkinsfile_CNP, Jenkinsfile_parameterized, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/AATHelper.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/BaseTest.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/Env.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/IdamApi.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/IdamHelper.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/OAuth2.java, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2210
Drop use of testing endpoint and use oauth2 flow instead
```
[ ] Yes
[x] No
```
=> RDM-2210: Use OAuth2 flow for functional tests

infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-2173
Switch SAAT DB to UK South
```
[ ] Yes
[x] No
```
=> Switch SAAT DB to UK South

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/helper/idam/IdamApi.java, build.gradle
=> added a content-length header for fixing functional tests

dependency-check-suppressions.xml
Another Emergency fix to dependency check
```
[ ] Yes
[x] No
```
=> [SKIP-PREVIEW] Suppress tomcat embedeed

infrastructure/variables.tf
N/A
Grant `jui_webapp` microservice S2S access to definition store service for all environments
```
[ ] Yes
[x] No
```
=> [SKIP-PREVIEW] Whitelist `jui_webapp` for S2S

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDM-2311
Implement nightly builds as per
https://tools.hmcts.net/confluence/display/RQA/CNP+-+Nightly+Pipeline
=> Add simplest nightly test run

infrastructure/aat.tfvars, infrastructure/preview.tfvars
RDM-2723
Point AAT and Preview back to Tactical IDAM
```
[ ] Yes
[x] No
```
=> RDM-2723: Revert to Tactical IDAM

infrastructure/aat.tfvars, infrastructure/preview.tfvars
Reverts hmcts/ccd-definition-store-api#111
=> RDM-2723: Switch to SIDAM

infrastructure/aat.tfvars, infrastructure/preview.tfvars
Reverts hmcts/ccd-definition-store-api#123
=> RDM-2723: Switch to back to TIDAM

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-2484
All the work to get the vault using ccd-$env exept removing the existing
local vault.  A few cleanup to check, where I've removed unused keys
(they're used in Jenkins but we won't need to use them in TF to copy
into the vault)
```
[ ] Yes
[x] No
```
=> [PREVIEW] Use Azure vault

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2484
Now the keys are gone we can remove the vaults.  Master should be 
deployed to other envs before we deply this.
```
[ ] Yes
[x] No
```
=> [PREVIEW] Remove actual local and Hashi vaults

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/CaseTypeTest.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/MultipleControllersEndpointIT.java, config/checkstyle/checkstyle.xml, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParserTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casefield/CaseFieldEntityMetadataFieldValidatorImplTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/fieldtype/FieldTypeValidationContextFactoryTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/JurisdictionParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportService.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EntityToDefinitionDataItemRegistryTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/EventRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/VersionedDefinitionRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/SearchInputCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/SearchResultCaseFieldEntity.java, rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ControllerExceptionHandler.java
https://tools.hmcts.net/jira/browse/RDM-2604
```
[ ] Yes
[x] No
```
=> Checkstyle fix imports

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-2635
```
[ ] Yes
[x] No
```
=> [PREVIEW] Infra: use ASP Resource Group

infrastructure/saat.tfvars
=> enable ES on Saat

Dockerfile, hub.Dockerfile
https://tools.hmcts.net/jira/browse/RDM-2687
```
[ ] Yes
[x] No
```
=> Dockerfile using CNP Java base image

build.gradle, dependency-check-suppressions.xml
- We don't manage the PG installation
- The version on Azure that we use is not impacted
https://tools.hmcts.net/jira/browse/RDM-3175
```
[ ] Yes
[x] No
```
=> Suppress CVE-2016-7048

infrastructure/sprod.tfvars
=> enable ES on sprod

infrastructure/demo.tfvars
=> enable ES on demo

elastic-search-support/src/main/resources/application.yml
=> RDM-3318: changed date field to allow storing empty values for dates

infrastructure/main.tf
=> add env var for ES scheme

dependency-check-suppressions.xml, infrastructure/main.tf, infrastructure/outputs.tf, infrastructure/variables.tf
Setting ES related env vars as outputs to make them visible for func tests
```
[ ] Yes
[ x] No
```
=> set ES env vars as outputs for func tests

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/elasticsearch/ElasticsearchBaseTest.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/elasticsearch/ElasticsearchImportDefinitionTest.java
=> [PREVIEW] update doc type in func tests from 'case' to '_doc'

elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/ElasticDefinitionImportListener.java, infrastructure/prod.tfvars, infrastructure/sprod.tfvars
=> log generated mapping in case of import failure

dependency-check-suppressions.xml
RDM-3549
Added suppress item cpe:/a:slf4j:slf4j:1.7.25 for CVE-2018-8088
```
[x] Yes
[ ] No
```
=> RDM-3549 Added suppress item cpe:/a:slf4j:slf4j:1.7.25 for CVE-2018-8088

build.gradle
https://tools.hmcts.net/jira/browse/RDM-2846
```
[ ] Yes
[ ] No
```
=> Bump dependency-management from 1.0.5.RELEASE to 1.0.6.RELEASE

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, infrastructure/main.tf, infrastructure/outputs.tf
https://tools.hmcts.net/jira/browse/RDM-2931
```
[ ] Yes
[ ] No
```
=> [PREVIEW] Use s2s vault

dependency-check-suppressions.xml
This is fixed when RDM-3796 lands.
https://tools.hmcts.net/jira/browse/RDM-3809
```
[ ] Yes
[ ] No
```
=> Temporary suppress CVE-2018-15756

excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchAliasFieldParser.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/SearchAliasFieldParserTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldEntity.java
https://tools.hmcts.net/jira/browse/RDM-3766
Bug fix for deriving collection field type for the search aliases
```
[ ] Yes
[x] No
```
=> RDM-3766 - bug fix - derive collection type for search alias fields

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-3796
* Bump spring
* Suppress suprious errors
* Suppress one that won't be fixed upstream
```
[ ] Yes
[ ] No
```
=> Bump springboot from 1.15.14 to 1.15.19 to resolve CVEs

.travis.yml, README.md
Remove last remnants of Oracle JDK from README and Travis
https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ ] No
```
=> Use OpenJDK everywhere

web.config
=> increase jvm mem

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DraftDefinitionController.java
=> added public access modifier to fix sonar quality gate error

repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-3576.xml
speed up case type def retrieval
```
[ ] Yes
[ x] No
```
=> added secondary db index for case type reference and version to

Dockerfile, Jenkinsfile_CNP, charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/requirements.lock, charts/ccd-definition-store-api/requirements.yaml, charts/ccd-definition-store-api/values.aat.template.yaml, charts/ccd-definition-store-api/values.template.yaml
https://tools.hmcts.net/jira/browse/RDM-3397
```
[ ] Yes
[ ] No
```
=> Enable Helm charts

infrastructure/saat.tfvars
N/A
Disable ES on SAAT
```
[ ] Yes
[x] No
```
=> Disable ES on SAAT

build.gradle
https://tools.hmcts.net/jira/browse/RDM-3790
```
[ ] Yes
[ ] No
```
=> Bump se.patrikerdes.use-latest-versions from 0.2.3 to 0.2.7

charts/ccd-definition-store-api/requirements.lock, charts/ccd-definition-store-api/requirements.yaml, infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
=> Switch to SIDAM for testing

infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
=> Move app onto its own ASP

infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
=> Move back to TIDAM

infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/RDM-3960
```
[ ] Yes
[ ] No
```
=> Use SIDAM on SAAT for testing

Dockerfile
https://tools.hmcts.net/jira/browse/RDM-4011
```
[ ] Yes
[ ] No
```
=> Use Kubernetes friendly Java image

infrastructure/main.tf, infrastructure/state.tf
https://tools.hmcts.net/jira/browse/RDM-4223
```
[ ] Yes
[ ] No
```
=> [PREVIEW] Remove remote Terraform state

lib/AI-Agent.xml
=> setup repositories appinsight instrumentation

lib/AI-Agent.xml
=> Appinsight drop type=

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars, infrastructure/variables.tf
Prod seems to be doing fine, so won't scale it just yet.  If the scaling
of Demo and AAT are seemless then will scale prod and sprod.
https://tools.hmcts.net/jira/browse/RDM-4387
```
[ ] Yes
[ ] No
```
=> [PREVIEW] Scale up AAT and Demo DBs

infrastructure/preview.tfvars
This reverts commit 5b7ee3831cc972aaf7e70b6eb4e47e2f00b1804a.
Actually remove this bit that wasn't meant to make it to master.
```
[ ] Yes
[ ] No
```
=> Revert "Remove: try to scale"

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityCanSaveDraftValidatorImpl.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/VersionedDefinitionRepositoryDecoratorTest.java, rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ImportAuditController.java
Changes for fixing sonar build complaints
```
[ ] Yes
[X ] No
```
=> fix sonar quality complaints

application/src/main/resources/bootstrap.yaml, build.gradle, charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.aat.template.yaml, charts/ccd-definition-store-api/values.template.yaml
https://tools.hmcts.net/jira/browse/RPE-1005
Fix password setup for the DB
and sonar issue failing master build
```
[ ] Yes
[ ] No
```
=> RPE-1005 Fix aks aat

charts/ccd-definition-store-api/values.template.yaml, infrastructure/preview.tfvars
Switch preview urls to look at SIDAM
=> Sidam aat preview

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/casetype/mapper/FieldTypeListItemMapper.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java, rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/BaseTypeController.java
=> RDM-3951-CaseType-Performance improvement for fixedListItems

repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-3681.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-4029.xml
The focus has been on coverage
Read optimisation over write
We'll see what the database delivers and then optimise
https://tools.hmcts.net/jira/browse/RDM-3681
```
[ ] Yes
[ ] No
```
=> Add DB indexes to all top queries

infrastructure/demo.tfvars
Switch Demo to look at AAT SIDAM
=> SIDAM idam_api_url

infrastructure/saat.tfvars
=> updating SIDAM values

Dockerfile
=> Update docker health checker

repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-4362.xml
https://tools.hmcts.net/jira/browse/RDM-4362
Liquibase should go first
```
[ ] Yes
[X ] No
```
=> RDM-4362 create PR for liquibase changes

infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/sprod.tfvars
https://tools.hmcts.net/jira/browse/RDM-4571
```
[ ] Yes
[ ] No
```
=> Deploy perftest env

infrastructure/ithc.tfvars, infrastructure/perftest.tfvars, lib/AI-Agent.xml
https://tools.hmcts.net/jira/browse/RDM-4694
```
[ ] Yes
[ ] No
```
=> Enable ithc env, plus some cleanups

build.gradle
https://tools.hmcts.net/jira/browse/RDM-4064
```
[ ] Yes
[ ] No
```
=> Bump Swagger2 from 2.9.0 to 2.9.2

aat/build.gradle, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/elasticsearch/ElasticsearchImportDefinitionTest.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/util/TestUtils.java
https://tools.hmcts.net/jira/browse/RDM-4345
Add retries to ES index verification in case ES has been setup in asynchronous mode
```
[ ] Yes
[x] No
```
=> RDM-4345 - add retry for ES index verification

repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepositoryTest.java
Jira Link:
https://tools.hmcts.net/jira/browse/RDM-4810
Change description
CaseTypeRepositoryTest - test methods have been added to improve the unit test coverage. The new test method helps to add CaseTypeACL information and retrieve the same.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X ] No
```
=> RDM-4810- To increase unit test coverage in "DefinitionStoreAPI" for CCD-AM Integration

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
=> Rdm 4523 complex types

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityFieldLabelValidator.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityFieldLabelValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-5105
Do not allow [] inside placeholder pattern. We cannot validate those as they are not defined in definition.
```
[ ] Yes
[x] No
```
=> Rdm 5105 Previously accepted definition fails validation

infrastructure/sandbox.tfvars
https://tools.hmcts.net/jira/browse/RDM-4793
The new Sandbox environment needs to be setup in subscription DCD-CFT-Sandbox
```
[ ] Yes
[x ] No
```
=> RDM-4793 - Added IDAM URL and Frontend URL for sandbox

application/src/test/resources/GetCaseTypesResponseForCCD_TestDefinition_V45.json, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-4272.xml
https://tools.hmcts.net/jira/browse/RDM-4272
Update the labels for Address Line 2 and 3
```
[ ] Yes
[x] No
```
=> RDM-4272-2: Update the labels for Address Line 2 and 3

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-3551
```
[ ] Yes
[ x] No
```
=> RDM-3551- upgraded owasp dependencycheck to 5.1.0

lib/AI-Agent.xml
… (CaseUsers data integration)
RDM-4863
Add instrumentation support for CCD-AM integration Phase 1 - CaseUsers data integration b/w CCD & AM.
```
No
```
=> RDM-4863 - Add instrumentation support for CCD-AM integration Phase 1

excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SpreadSheetValidationMappingEnum.java
https://tools.hmcts.net/jira/browse/RDM-5520
Remove FixedList ListElement length validation as it has no restriction in the DB
```
[ ] Yes
[x] No
```
=> RDM-5520 - Remove FixedList ListElement length validation

dependency-check-suppressions.xml
we'll review them and fix for good as part of https://tools.hmcts.net/jira/browse/RDM-3796
```
[ ] Yes
[ x] No
```
=> temporarily added suppression to fix broken build

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/ImportDefinitionTest.java
https://tools.hmcts.net/jira/browse/RDM-5519
Fix the breaking build.
```
[ ] Yes
[x] No
```
=> RDM-5519: Disabling the test case as it is breaking the build. Will fix it in next iteration.

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/ImportDefinitionTest.java
https://tools.hmcts.net/jira/browse/RDM-5519
```
[ ] Yes
[x] No
```
=> Rdm 5519 master build fix

build.gradle
Fixing CVE-2019-10086.
```
[ ] Yes
[ x] No
```
=> CVE-2019-10086 fix.

build.gradle, dependency-check-suppressions.xml, elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/client/HighLevelCCDElasticClient.java, excel-importer/build.gradle
https://tools.hmcts.net/jira/browse/RDM-6331
Address current CVEs by bumping dependency versions and clean up redundant CVE suppressions.
```
[ ] Yes
[x] No
```
=> Address current CVEs and clean up suppressions

domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WebhookParser.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventWebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/WebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WebhookType.java, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.1.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.2.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.3.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6336.xml, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeObjectGraphTest.java
https://tools.hmcts.net/jira/browse/RDM-6336
https://tools.hmcts.net/jira/browse/RDM-6246
```
[ ] Yes
[x] No
```
=> Update RC with perf improvements 

domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/WebhookParser.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventWebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/WebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WebhookType.java, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.1.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.2.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6246.3.xml, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeObjectGraphTest.java
Prod hotfix containing perf improvement for definition store 
https://github.com/hmcts/ccd-definition-store-api/pull/463
https://tools.hmcts.net/jira/browse/RDM-6246
```
[ ] Yes
[x] No
```
=> prod performance improvement hot fix 

dependency-check-suppressions.xml, web.config
https://tools.hmcts.net/jira/browse/RDM-5533
Disable `X-Powered-By` header
```
[ ] Yes
[x] No
```
=> RDM-5533 Disable X-Powered-By header

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WizardPageField.java
https://tools.hmcts.net/jira/browse/RDM-6887
Removed displayContext from WizardPageField
```
[ ] Yes
[X ] No
```
=> RDM-6887 Remove duplicate display context from data store endpoint

Jenkinsfile_CNP
Reverts hmcts/ccd-definition-store-api#495
=> Revert "re enable legacy deployment to fix broken ithc env"

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationError.java
=> Fixing in sonar error.

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/ValidationError.java
=> fix sonar issue

charts/ccd-definition-store-api/values.preview.template.yaml
=> Rdm 7196 second attempt

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDM-7116
```
[ ] Yes
[x] No
```
=> RDM-7116 rm-ase-envir

infrastructure/aat.tfvars, infrastructure/ithc.tfvars, infrastructure/perftest.tfvars, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/saat.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars
Reverts hmcts/ccd-definition-store-api#511
=> Revert "Removed unwanted env (ASE) files"

domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDM-7380
https://tools.hmcts.net/jira/browse/RDM-7312
Code coverage issues fixed for banner changes
```
[ ] Yes
[X ] No
```
=> Rdm 7380: Fix code coverage issue on Banner Changes

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/JurisdictionUiConfigService.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/JurisdictionUiConfigServiceImpl.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/JurisdictionUiConfigServiceImplTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ServicesAutowiringTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/JurisdictionUiConfigParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/util/mapper/ColumnName.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/JurisdictionUiConfigParserTest.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/JurisdictionUiConfigRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/JurisdictionUiConfigEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/JurisdictionUiConfig.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/JurisdictionUiConfigResult.java, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-6965.xml, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/JurisdictionUiConfigRepositoryTest.java, rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiController.java, rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiControllerTest.java
https://tools.hmcts.net/jira/browse/RDM-6965
Introduce new jurisdiction_ui_config definition table.
Introduce jurisdiction level shuttering.
```
[ ] Yes
[x] No
```
=> RDM-6965 - Jurisdiction-Level Shuttering

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java, build.gradle
https://tools.hmcts.net/jira/browse/RDM-6955
Duplicate Object IDs Not Reported. Up the version of befta.
```
[ ] Yes
[ ] No
```
=> Rdm 6955 Duplicate Object IDs Not Reported

build.gradle
=> upgrade to befta fw 1.1.1

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml
=> RDM-7899-Slack

aat/src/aat/resources/features/F-077/S-331.td.json, aat/src/aat/resources/features/F-079/S-507.td.json, aat/src/aat/resources/features/F-079/S-508.td.json, build.gradle
https://tools.hmcts.net/jira/browse/RDM-7986
Post-release cleanup.
```
[ ] Yes
[X] No
```
=> refactor test data to reuse common objects

.github/workflows/swagger.yml, src/test/java/uk/gov/hmcts/ccd/swagger/SwaggerPublisher.java
https://tools.hmcts.net/jira/browse/RDM-7740
Establish automated publishing of swagger spec with a github workflow (fix applied)
```
[ ] Yes
[X] No
```
=> introduce test class and github action to publish swagger specs

.github/workflows/swagger.yml, application/src/test/java/uk/gov/hmcts/ccd/definition/store/swagger/SwaggerPublisher.java
=> move test file and use it from its better location

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/MultipleControllersEndpointIT.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/JurisdictionServiceImpl.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/JurisdictionRepository.java
Reverts hmcts/ccd-definition-store-api#546
=> Revert "Rdm 7162"

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/perftest.tfvars, infrastructure/prod.tfvars
=> Add missing vars back

application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/RDM-8094
disable issuer validation until idam migration is complete
```
[ ] Yes
[ x] No
```
=> RDM-8094 - disable issuer validation until idam migration is complete

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreBeftaRunner.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java, build.gradle
=> Fix build issue

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ControllerExceptionHandler.java
=> Set order on preferred exception handler

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaycontextparameter/DateTimeDisplayValidatorImpl.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaycontextparameter/DateTimeEntryValidatorImpl.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/displaycontextparameter/DisplayContextParameterValidator.java
https://tools.hmcts.net/jira/browse/RDM-8251
Separate display/entry regex; add exclusions to entry
```
[ ] Yes
[x] No
```
=> RDM-8251 - Separate display/entry regex; add exclusions to entry

build.gradle
=> Fix CVE-2020-9488

Jenkinsfile_CNP, build.gradle, charts/ccd-definition-store-api/values.preview.template.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-7650
```
[ ] Yes
[x] No
```
=> RDM-7650 use JSON Def file functionality in befta 

build.gradle
https://tools.hmcts.net/jira/browse/RDM-8393
Update health-spring-boot-starter to 0.0.5
```
[ ] Yes
[ X] No
```
=> RDM-8393 update health-spring-boot-starter

aat/src/aat/resources/features/F-079/S-508.td.json, aat/src/aat/resources/features/F-080/S-080.1.td.json
=> Fixing live from date issues

Jenkinsfile_CNP, dependency-check-suppressions.xml
=> Empty Commit

elastic-search-support/src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/RDM-8552
Add last_state_modified_date ES mapping
```
[ ] Yes
[x] No
```
=> RDM-8552 - Add last_state_modified_date ES mapping

aat/build.gradle, aat/src/aat/resources/features/F-000/F-000.feature, dependency-check-suppressions.xml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDM-8629
Change description
Linked F-000 as smoke test
```
[ ] Yes
[x] No
```
=> Linked F-000 as smoke test

application/build.gradle, build.gradle, dependency-check-suppressions.xml, integration-tests/build.gradle
RDM-8733: CVE-2020-13692
[RDM-8733] (https://tools.hmcts.net/jira/browse/RDM-8733).
CVE-2020-13692
=> RDM-8733: CVE-2020-13692

elastic-search-support/src/main/resources/casesIndexSettings.json
https://tools.hmcts.net/jira/browse/RDM-8581
Updating total-fields.limit to 8000
```
[ ] Yes
[X] No
```
=> RDM-8581 : Updating total-fields.limit

domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java
https://tools.hmcts.net/jira/browse/RDM-8814
Fixed code analysis issues
```
[ ] Yes
[ X] No
```
=> RDM-8814: Data store develop branch code coverage issue

charts/ccd-definition-store-api/values.preview.template.yaml
=> Testing ES on defination-store preview

build.gradle, dependency-check-suppressions.xml
=> Fixed CVE 11996 issue

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerService.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImpl.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImplTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/BannerRepository.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/BannerRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-8892
Clean up any existing banners on every import
```
[ ] Yes
[x] No
```
=> RDM-8892 - Clean up any existing banners on every import

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerService.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImpl.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/banner/BannerServiceImplTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/BannerParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/BannerParserTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/BannerRepository.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/BannerRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-8515
Support empty Banner tab
```
[ ] Yes
[x] No
```
=> RDM-8515 - Support empty Banner tab

.github/renovate.json, dependency-check-suppressions.xml
=> Rdm 8808 renovate

build.gradle, charts/ccd-definition-store-api/values.preview.template.yaml
none
Enable elastic search, for use of other apps requiring an ES-enabled deployment of def store on preview.
```
[X] Yes
[ ] No
```
=> enable elastic search

dependency-check-suppressions.xml
=> Update dependency-check-suppressions.xml for Green Master Build

charts/ccd-definition-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDM-9143
Enable ES
```
[ ] Yes
[X] No
```
=> RDM-9143: Enable elastic search

repository/src/main/resources/db/changelog/db.changelog-master.xml
=> Correct 19.1 liquibase changelog ordering

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ProxyController.java
=> suppressed sonar issue

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/ProxyController.java
=> suppressing sonar issue

aat/src/aat/resources/features/F-079/F-079.feature, aat/src/aat/resources/features/F-089/F-089.feature
=> Ignore failing FT

aat/src/aat/resources/features/F-079/F-079.feature, aat/src/aat/resources/features/F-079/S-508.td.json, aat/src/aat/resources/features/F-089/F-089.feature, aat/src/aat/resources/features/F-089/S-089.2.td.json
Fix 2 funstional tests that were ignored during release 19.1
https://tools.hmcts.net/jira/browse/RDM-9241
```
[ ] Yes
[x] No
```
=> Fix Functional tests

application/src/main/resources/application.properties, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseFieldParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/CaseTypeParser.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseEventParserTest.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/AuthorisationCaseFieldParserTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseFieldEntityUtil.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/Authorisation.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ComplexFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventWebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/FieldTypeListItemEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/WebhookEntity.java, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-8692.xml
=> RDM-8962 CI-CD Improve performance of definition importing

aat/src/aat/resources/features/F-089/S-089.2.td.json
=> assert case fields unordered

charts/ccd-definition-store-api/values.preview.template.yaml, elastic-search-support/src/main/resources/application.yml, elastic-search-support/src/main/resources/casesIndexSettings.json, elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json, elastic-search-support/src/test/resources/integration/single_casetype_index.json
https://tools.hmcts.net/jira/browse/RDM-8698
Exact match queries on phone numbers with or without spaces
```
[ ] Yes
[X] No
```
=> RDM-8698 : exact match queries on phone numbers with or without spaces

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9446
Adding a temporary suppression for CVE-2020-7019 and CVE-2020-24616
```
[ ] Yes
[X] No
```
=> Adding a temporary suppression.

build.gradle
=> upgrade to latest fw

elastic-search-support/src/main/resources/application.yml, elastic-search-support/src/main/resources/casesIndexSettings.json, elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json, elastic-search-support/src/test/resources/integration/single_casetype_index.json
Pull #683 from release cut
```
[ ] Yes
[ ] No
```
=> Revert rdm 8698

charts/ccd-definition-store-api/values.preview.template.yaml
=> Set ES host back to develop PR

charts/ccd-definition-store-api/values.preview.template.yaml
=> Revert user-profile to develop

application/src/main/resources/application.properties, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/question/ChallengeQuestionTabService.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/question/ChallengeQuestionTabServiceImpl.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/ChallengeQuestionTabServiceImplTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/ChallengeQuestionTabRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/ChallengeQuestion.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/ChallengeQuestionsResult.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/ChallengeQuestionTabRepositoryTest.java, rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiController.java, rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/endpoint/DisplayApiControllerTest.java
https://tools.hmcts.net/jira/browse/RDM-9577
Introduce getChallengeQuestions API
```
[ ] Yes
[x] No
```
=> RDM-9577 - Introduce getChallengeQuestions API

build.gradle
=> Befta fw bump up

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-9479
Cleanup and formatting
```
[ ] Yes
[x] No
**```**
=> cleanup and formatting

build.gradle
=> Upgrade to latest, fixed fw version.

aat/src/aat/resources/features/F-089/F-089.feature
https://tools.hmcts.net/jira/browse/RDM-9395
```
[ ] Yes
[X] No
```
=> Removed @Ignore for @S-089.1

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/SwaggerGeneratorTest.java, build.gradle
https://tools.hmcts.net/jira/browse/RDM-9654
```
[ ] Yes
[X] No
```
=> Removed PMD reference

build.gradle
https://tools.hmcts.net/jira/browse/RDM-9114
Migrate DefinitionStore to use HMCTS Gradle Java Plugin
```
[ ] Yes
[x ] No
```
=> bump up hmcts plugin

elastic-search-support/src/main/resources/application.yml, elastic-search-support/src/main/resources/casesIndexSettings.json, elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json, elastic-search-support/src/test/resources/integration/single_casetype_index.json
=> Revert 8698

application/build.gradle, charts/ccd-definition-store-api/values.yaml, liquibase.gradle
=> Disable gssEncMode

repository/src/main/resources/db/changelog/db.changelog-master.xml
=> Add to RDM-9994 to master changelog

repository/src/main/resources/db/changelog/db.changelog-rdm-9031.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-9555.xml
=> RDM-9824: Validchecksum tag added to 9031 and 9555

dependency-check-suppressions.xml
=> suppress temporarily

README.md, application/src/main/resources/application.properties, charts/ccd-definition-store-api/values.yaml, docker-compose.yml
https://tools.hmcts.net/jira/browse/ACA-68 (NoC Request API)
Add MCA to list of authorised services that can communicate with this service
```
[ ] Yes
[X] No
```
=> Aca 68 - Add MCA to list of S2S authorised services

elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/ElasticsearchError.java, elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/ElasticsearchErrorHandler.java, elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/ElasticsearchErrorMessageBuilder.java, elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/FieldTypeMappingErrorMessageBuilder.java, elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/MaxFieldLimitErrorMessageBuilder.java, elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/ElasticsearchErrorTest.java, elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/ElasticsearchErrorHandlerTest.java, elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/ElasticsearchErrorMessageBuilderTest.java, elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/FieldTypeMappingErrorMessageBuilderTest.java, elastic-search-support/src/test/java/uk/gov/hmcts/ccd/definition/store/elastic/exception/handler/MaxFieldLimitErrorMessageBuilderTest.java
Fix checkstyle errors that were breaking pipeline build, see Jenkins build 280
https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_CDM%2Fccd-definition-store-api/detail/PR-575/280/
```
[ ] Yes
[X] No
```
=> Fix checkstyle issues

charts/ccd-definition-store-api/values.preview.template.yaml
=> Updated user-profile-api-pr number

repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-9031.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-9555.xml
=> Adjust develop merge resolutions

build.gradle
=> Revert befta in develop

aat/src/aat/resources/features/F-080/F-080.feature, aat/src/aat/resources/features/F-086/F-086.feature, aat/src/aat/resources/features/F-089/F-089.feature, aat/src/aat/resources/features/F-090/F-090.feature
=> Temporarily disable expected failing FT

elastic-search-support/src/main/resources/casesIndexSettings.json, elastic-search-support/src/test/resources/integration/multi_casetypes_indices.json, elastic-search-support/src/test/resources/integration/single_casetype_index.json
https://tools.hmcts.net/jira/browse/RDM-8698
```
[ ] Yes
[X] No
```
=> RDM-8698 : Elasticsearch exact match queries on phone numbers with spaces never return results

aat/src/aat/resources/features/F-093/S-600.3.td.json, aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.1.td.json, build.gradle
=> bump befta

application/src/main/java/uk/gov/hmcts/ccd/definition/store/AliasWebConfig.java, application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java, charts/ccd-definition-store-api/values.preview.template.yaml, liquibase.gradle
https://tools.hmcts.net/jira/browse/RDM-10301
```
[ ] Yes
[ ] No
```
=> Release cut demo deployment fix

aat/src/aat/resources/features/F-094 NoC ChallengeQuestions/S-094.1.td.json
=> declare collection as unordered

charts/ccd-definition-store-api/values.preview.template.yaml, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/SearchAliasFieldRepository.java
https://tools.hmcts.net/jira/browse/RDM-10199
Updated the JPA Query to remove expensive cross join.
```
[ ] Yes
[ X] No
```
=> RDM-10199 Update the query to get rid of the cross join.

charts/ccd-definition-store-api/values.preview.template.yaml, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/SearchAliasFieldRepository.java
Reverts hmcts/ccd-definition-store-api#830
=> Revert "RDM-10199 Update the query to get rid of the cross join."

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10294
Fix All Recent CVEs in All CCD Apps
```
[ ] Yes
[X] No
```
=> RDM-10294 Fix All Recent CVEs in All CCD Apps

elastic-search-support/src/main/resources/casesIndexSettings.json, repository/src/main/resources/db/changelog/db.changelog-master.xml
=> Add back db changelog 

charts/ccd-definition-store-api/values.preview.template.yaml, repository/src/main/resources/db/changelog/db.changelog-master.xml, repository/src/main/resources/db/changelog/db.changelog-rdm-9220.xml, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepositoryTest.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-9220
```
[ ] Yes
[X] No
```
=> RDM-9220 : Create Indexes on AAT Missing Compared to Demo -Master

repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/SearchAliasFieldRepository.java
https://tools.hmcts.net/jira/browse/RDM-10199
Updated the JPA Query to remove expensive cross join.
```
[ ] Yes
[X] No
```
=> RDM-10199 Update the query to remove a cross join.

charts/ccd-definition-store-api/values.preview.template.yaml, dependency-check-suppressions.xml
=> update data store develop pr

build.gradle
https://tools.hmcts.net/jira/browse/RDM-10616
Bumped befta-fw version to 6.3.0
```
[ ] Yes
[x] No
```
=> RDM-10616: Bump befta-fw version to 6.3.0

charts/ccd-definition-store-api/values.preview.template.yaml, dependency-check-suppressions.xml
Suppressed CVE issues
```
[ ] Yes
[X ] No
```
=> Suppressed CVE issues

repository/src/main/resources/db/migration/V20201208__RDM-10261_COR_CaseRoleId_DynamicList.sql
https://tools.hmcts.net/jira/browse/RDM-10261
Updated ChangeOrganisationRequest.CaseRoleId from Text to the DynamicList field type.
COR.CaseRoleId should have no data in prod (checked in prod on 04/12/2020) and there should be no ES reindexing needed.
```
[ ] Yes
[X ] No
```
=> RDM-10261 Update COR.CaseRoleId from Text to DynamicList type

excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
=> Release cut 20.2 revised

repository/src/main/resources/db/migration/V20201208__RDM-10261_COR_CaseRoleId_DynamicList.sql
Reverts hmcts/ccd-definition-store-api#863
=> Revert "RDM-10261 Update COR.CaseRoleId from Text to DynamicList type"

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10678
[20.4&20.5] Regular CI Maintenance
```
[ ] Yes
[X] No
```
=> RDM-10678 temporary suppressions

elastic-search-support/build.gradle
https://github.com/testcontainers/testcontainers-java/issues/3574
=> Update testcontainers for Docker pull fix

elastic-search-support/build.gradle
https://tools.hmcts.net/jira/browse/RDM-10854
Update testcontainers for Docker pull fix
See https://github.com/testcontainers/testcontainers-java/issues/3574
```
[ ] Yes
[x] No
```
=> RDM-10854 - Update testcontainers for Docker pull fix

.github/workflows/swagger.yml, aat/build.gradle
https://tools.hmcts.net/jira/browse/RDM-10747
```
[ ] Yes
[X] No
```
=> RDM-10747 : Swagger Publishing Workflow Broken - Definition Store API

charts/ccd-definition-store-api/values.preview.template.yaml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceValidator.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/casetype/CaseTypeEntityReferenceValidatorTest.java
https://tools.hmcts.net/jira/browse/RDM-10843
Added the CaseType reference validation to prevent ES failures.
```
[ ] Yes
[X ] No
```
=> RDM-10843 Add CaseType reference validation

aat/src/aat/resources/features/F-093/S-600.2.td.json, aat/src/aat/resources/features/F-093/S-600.4.td.json, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParser.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ParserFactory.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/model/DefinitionDataItem.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidator.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventCaseFieldComplexTypeParserTest.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/parser/EventParserTest.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidatorTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/WizardPageComplexFieldOverride.java, repository/src/main/resources/db/migration/V20201217_9754__RDM-9754_retain_hidden_value_case_event_to_complex_type.sql
=> Develop compilation issue patch

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/util/DatabaseTableClearer.java, charts/ccd-definition-store-api/values.preview.template.yaml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterService.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/display/DisplayGroupAdapterServiceTest.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/parser/ChallengeQuestionParser.java, repository/build.gradle, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeLiteEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ChallengeQuestionTabEntity.java, repository/src/main/resources/db/migration/V20210121_10770__event_case_field_complex_index.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepositoryTest.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/ChallengeQuestionTabRepositoryTest.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/TestConfiguration.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/TestHelper.java
Perf improvements..
1. Changed EAGER fetch to LAZY in CaseTypeLiteEntity
2. Referred CaseTypeLiteEntity in ChallengeQuestionTabEntity
3. Added tests to verify SQL statements count for each operation (useful against N+1 problem)
https://tools.hmcts.net/jira/browse/RDM-10770
```
[ ] Yes
[X] No
```
=> RDM-10770 - perf improvements

aat/src/aat/resources/features/common/fieldtypes/AllValidBaseTypeArrayPayload.td.json, aat/src/aat/resources/features/common/fieldtypes/base/BaseDynamicMultiSelectListFieldType.td.json, aat/src/aat/resources/features/common/fieldtypes/base/BaseDynamicRadioListFieldType.td.json
=> Fix failing functional test

build.gradle
=> Updated befta version

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
=> RDM-10604_2

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/TestDataLoaderMain.java, aat/src/aat/resources/features/F-093/F-093.feature, aat/src/aat/resources/features/F-093/S-600.5.td.json, aat/src/aat/resources/features/F-093/S-600.6.td.json, build.gradle
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 adding additional functional test to cover work implemented in RDM-9754
* RDM-10823 minor tweaks
* RDM-10823 minor tweaks
* RDM-10823 minor tweaks
* RDM-10823 updated befta
* Update build.gradle
Co-authored-by: Ashley Noronha <ashleydeannoronha@gmail.com>
Please remove this line and everything above and fill the …
=> RDM-10823 retain hidden value functional tests (Master)(#918)

repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
=> Fix develop build

dependency-check-suppressions.xml
=> Suppress CVE-2020-7021

dependency-check-suppressions.xml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11087
```
[ ] Yes
[X] No
```
=> RDM-11087 Upgrade to Postgres 11 on Perftest

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11087
```
[ ] Yes
[X] No
```
=> RDM-11087 Postgres11 upgrade clean-up 

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11362
CVE-2020-26939 (Definition Store)
```
[ ] Yes
[X] No
```
=> RDM-11362 CVE-2020-26939 (Definition Store)

build.gradle
https://tools.hmcts.net/jira/browse/RDM-11506
CVE-2021-25122 (Def Store)
```
[ ] Yes
[X] No
```
=> RDM-11506 CVE-2021-25122 (Def Store)

charts/ccd-definition-store-api/values.preview.template.yaml
=> correct es wiring on preview

build.gradle, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11090
```
[X ] Yes
[ ] No
```
=> RDM-11090: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on ITHC

infrastructure/main.tf
=> Rd11090 ithc

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.1_Get_CaseType.td.json
https://tools.hmcts.net/jira/browse/RDM-11933
Case reference type changed to TEXT
```
[ ] Yes
[X ] No
```
=> RDM-11933: Case reference type changed to TEXT

infrastructure/main.tf
=> Update main.tf fix-demo

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json, dependency-check-suppressions.xml, repository/src/main/resources/db/migration/V20210413_12014__RDM-12014_previous_organisations.sql
https://tools.hmcts.net/jira/browse/RDM-12014
updated labels in previous organisations to include spaces 
```
[ ] Yes
[X] No
```
=> RDM-12014 update labels to include spaces in previous organisations

elastic-search-support/src/main/java/uk/gov/hmcts/ccd/definition/store/elastic/client/HighLevelCCDElasticClient.java
https://tools.hmcts.net/jira/browse/RDM-12107?filter=-1
Fortify Issue 13318076 - Unreleased Resource: Streams - High
```
[ ] Yes
[X] No
```
=> RDM-12107 Fortify Issue 13318076 - Unreleased Resource: Streams - High

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDM-11095
```
[ ] Yes
[X ] No
```
=> RDM-11095: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on PROD

application/src/main/resources/bootstrap.yaml, charts/ccd-definition-store-api/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/RDM-11095
```
[ ] Yes
[X ] No
```
=> RDM-11095: CCD-DEFINITION-STORE: Upgrade to Postgres 11 on AAT

charts/ccd-definition-store-api/values.aat.template.yaml
=> Correct staging db name

build.gradle, repository/build.gradle
https://tools.hmcts.net/jira/browse/CCD-1137
CVE-2020-10693 on Def Store
```
[ ] Yes
[x] No
```
=> CCD-1137 CVE-2020-10693 on Def Store

application/src/main/resources/bootstrap.yaml, charts/ccd-definition-store-api/values.aat.template.yaml, infrastructure/main.tf
=> RDM-11095 - Cleanup Definition Store DB migration

charts/ccd-definition-store-api/values.preview.template.yaml
=> update user profile develop pr

aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/S-098.1.td.json, aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/S-098.2.td.json, aat/src/aat/resources/features/F-098 rename of UserRole to AccessProfile/S-098.3.td.json, build.gradle
=> Update befta test files path

Jenkinsfile_CNP
=> Remove ordering assertions for collections

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json
https://tools.hmcts.net/jira/browse/CCD-1243
```
[ ] Yes
[ ] No
```
=> assert unordered equivalence

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1262
CVE-2021-22118 in CCD Definition Store API
```
[ ] Yes
[x] No
```
=> CCD-1262 CVE-2021-22118 in CCD Definition Store API suppress CVE

aat/src/aat/resources/features/F-082/F-082.feature
=> disable slow test temporarily

Jenkinsfile_CNP, repository/src/main/resources/db/migration/V20210706_12651__RDM-12651_noc_answer_field_length.sql
https://tools.hmcts.net/jira/browse/RDM-12651
Increase challenge_question.answer_field column length to 5000 to support services 
```
[ ] Yes
[x] No
```
=> RDM-12651 - Increase NoC answer field length

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RDM-11779
remove enableDbMigration from Jenkinsfile_CNP
```
[ ] Yes
[x] No
```
=> remove enableDbMigration from Jenkinsfile_CNP

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1655
Tolerate missing def store instances
```
[ ] Yes
[X] No
```
=> Tolerate missing def store instances when building first time

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
https://tools.hmcts.net/jira/browse/CCD-1592
Integrate Fortify Scan into Nightly Pipelines - Definition Store
```
[ ] Yes
[x] No
```
=> Nightly master ccd 1592

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/tests/functional/CaseTypeTest.java
=> Remove test annotaion

dependency-check-suppressions.xml
Suppress apache-commons-compress CVE's
To be fixed in:
[CCD-1696](https://tools.hmcts.net/jira/browse/CCD-1696)
[CCD-1697](https://tools.hmcts.net/jira/browse/CCD-1697)
[CCD-1698](https://tools.hmcts.net/jira/browse/CCD-1698)
[CCD-1699](https://tools.hmcts.net/jira/browse/CCD-1699)
```
[ ] Yes
[x] No
```
=> Suppress apache-commons-compress CVE's

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CCD-1716
Double the storage of def store DB
```
[ ] Yes
[X] No
```
=> double the storage of def store DB

charts/ccd-definition-store-api/Chart.yaml, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java, repository/src/main/resources/db/migration/V20210802_12678__RDM-12678-SearchParty_ComplexType.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-12678
Add a new standard base complex type so that global search can store the searchable party information in a standard form.
```
[ ] Yes
[X] No
```
=> RDM-12678 - Add SearchParty complex base type

dependency-check-suppressions.xml, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/Authorisation.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/BannerEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/CaseTypeEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/ComplexFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/DisplayGroupEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventCaseFieldEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventLiteEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/EventWebhookEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/GenericLayoutEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/JurisdictionUiConfigEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/StateEntity.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepositoryTest.java
Reverts hmcts/ccd-definition-store-api#1049
=> Revert "Change EAGER fetch in relations to LAZY"

dependency-check-suppressions.xml
Suppress CVE-2021-28170 & CVE-2021-22119
```
[ ] Yes
[ ] No
```
=> Suppress CVE's

infrastructure/perftest.tfvars, infrastructure/prod.tfvars
=> scale p def store db temporarily

infrastructure/perftest.tfvars, infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/CCD-1178
correct sku name
```
[ ] Yes
[X] No
```
=> Update sku name

dependency-check-suppressions.xml
Suppress CVE-2020-23171
```
[ ] Yes
[x] No
```
=> Suppress CVE-2020-23171

excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java, repository/src/main/resources/db/migration/V20210916_12826__RDM-12826_TTL_ComplexType.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-12826
Establish the new TTL Complex BaseType
```
[ ] Yes
[x] No
```
=> RDM-12826 - add TTL complex base type

dependency-check-suppressions.xml
none
Extend suppression until dates to unblock pipelines
```
[ ] Yes
[X] No
```
=> Extend suppression until dates to unblock pipelines

dependency-check-suppressions.xml, elastic-search-support/src/main/resources/globalSearchCasesMapping.json
https://tools.hmcts.net/jira/browse/RDM-12770
Align Global Search field names with existing CCD CaseDetails
```
[ ] Yes
[ ] No
```
=> RDM-12770 Align Global Search field names with existing CCD CaseDetails

Jenkinsfile_CNP, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1736
```
[ ] Yes
[x] No
```
=> Update Jenkinsfile_CNP syncBranchesWithMaster

rest-api/src/main/java/uk/gov/hmcts/ccd/definition/store/rest/service/AzureImportAuditsClient.java, rest-api/src/test/java/uk/gov/hmcts/ccd/definition/store/rest/service/AzureImportAuditsClientTest.java
https://tools.hmcts.net/jira/browse/CCD-572
1. Added mock test for empty list returned when fetching prefix from Az blob storage.
2. Added additional checks in while loop and conditional break. 
3. Confirmed successful grade build of project
```
[ ] Yes
[X] No
```
=> CCD-572 Fix for looping issue when fetching Az blob segments

dependency-check-suppressions.xml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParser.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/showcondition/ShowConditionParserTest.java
https://tools.hmcts.net/jira/browse/RDM-10133
Support for AND, OR and Parenthesis 
```
[ ] Yes
[X] No
```
=> RDM-10133 showCondition support for AND, OR and Parenthesis 

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/HighLevelDataSetupApp.java
=> temp disable HLDS

build.gradle
https://tools.hmcts.net/jira/browse/CCD-2333
```
[ ] Yes
[ ] No
```
=> update log4j version to 2.15.0

repository/src/main/resources/db/migration/V20220110_1703__CCD-1703_complex_field_index.sql
https://tools.hmcts.net/jira/browse/CCD-1703
```
[ ] Yes
[ ] No
```
=> introduced new index on complex_field

excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SpreadSheetValidationMappingEnum.java, repository/src/main/resources/db/migration/V20220112_2388__CCD-2388_increase_complex_field_label_column_size.sql
https://tools.hmcts.net/jira/browse/CCD-2388
```
[ ] Yes
[ ] No
```
=> increased complex_field->label max size to 500

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/HighLevelDataSetupApp.java
=> temp disable hlds on aat

Jenkinsfile_CNP, aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/S-099.1_Get_ConditionalsCaseType.td.json, aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/S-099.1_Get_RetainHiddenValueCaseType.td.json, aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/S-099.1_Get_TabsCaseType.td.json
[RDM-12677](https://tools.hmcts.net/jira/browse/RDM-12677) _"Global Search"_ (epic)
Global search FTA patch
```
[ ] Yes
[x] No
```
=> Global search FTA patch

aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/CCD-2455
corrections and cleanups post GS release
```
[ ] Yes
[X] No
```
=> re-enable hlds on aat

aat/src/aat/resources/features/common/fieldtypes/AllValidBaseTypeArrayPayload.td.json, aat/src/aat/resources/features/common/fieldtypes/base/BaseWaysToPayFieldType.td.json, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/rest/BaseTypeControllerTests.java, elastic-search-support/src/main/resources/application.yml, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java, repository/src/main/resources/db/migration/V20220110_13063__RDM-13063_WaysToPay_base_type.sql
https://tools.hmcts.net/jira/browse/RDM-13063
Add new WaysToPay base type
```
[ ] Yes
[x] No
```
=> RDM-13063 - Add new WaysToPay base type

build.gradle, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeUtils.java, repository/src/main/resources/db/migration/V20211220_12979__RDM-12979__FlagsFlagDetails.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/FieldTypeRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDM-12979
```
[ ] Yes
[ X] No
```
=> RDM-12979: Establish new Flags and FlagDetail base types

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Amending suppression dates by 1 month
```
[ ] Yes
[X ] No
```
=> Amending suppression dates by 1 month

Jenkinsfile_CNP, aat/build.gradle, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/DefinitionStoreTestAutomationAdapter.java, aat/src/aat/java/uk/gov/hmcts/ccd/definitionstore/befta/HighLevelDataSetupApp.java, build.gradle, repository/build.gradle, repository/src/test/resources/test.properties
https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
- Upgrade to relevant dependencies
- Upgrade BEFTA-FW version to 8.7.1
- Updated and introduced env variables to Jenkins_CNP
- Add bean-overiding for tests - spring.main.allow-bean-definition-overriding
```
[ ] Yes
[ x] No
```
=> remove jcenter and upgrade dependencies

dependency-check-suppressions.xml, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/SpreadSheetValidationMappingEnum.java, repository/src/main/resources/db/migration/V20220209_2554__CCD-2554_increase_event_case_field_complex_type_label_column_size.sql
https://tools.hmcts.net/jira/browse/CCD-2554
```
[ ] Yes
[ ] No
```
=> increased maximum field length for Labels in EventToComplexTypes to 500

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2638
https://tools.hmcts.net/jira/browse/CCD-2625
https://tools.hmcts.net/jira/browse/CCD-2586
https://tools.hmcts.net/jira/browse/CCD-2612
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832
```
[ ] Yes
[ X] No
```
=> CVE fix definition store

charts/ccd-definition-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
=> Upgrade to Latest Base Helm Charts

dependency-check-suppressions.xml
Also added dates if they do not have them
https://tools.hmcts.net/jira/browse/CCD-2497
Amended the CVE suppression date by a month
```
[ ] Yes
[ X] No
```
=> Amend Suppression Dates

build.gradle
-
Bump up test definitions version
```
[ ] Yes
[X] No
```
=> bump up test definitions version to latest stable

aat/src/aat/resources/features/F-097 RoleToAccessProfiles/S-097.8.td.json
Patch to fix failing functional test in the master pipeline - S-097.8
```
[ ] Yes
[X] No
```
=> PR to fix failing functional test

charts/ccd-definition-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-2810
```
[ ] Yes
[ ] No
```
=> memory adjustment for preview

repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
Reverts hmcts/ccd-definition-store-api#1186
=> Revert "ccd-2527 clean up, adding delete sqls"

aat/src/aat/resources/features/F-095 Publish Flag in Case Event/S-095.12_Get_CaseType.td.json, repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
-
fix data - assert states in any order
```
[ ] Yes
[X] No
```
=> assert states in any order

repository/src/main/resources/db/useful-queries/Remove all definitions for a case type.sql
CFTS-2201
facilitate clean up of multiple case types in 1 go
```
[ ] Yes
[X] No
```
=> facilitate clean up of multiple case types in 1 go

aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/F-099_Get_GlobalSearchSchemaSnapshot.td.json, aat/src/aat/resources/features/F-099 SearchParty (GlobalSearch)/S-099.1_Get_GlobalSearchCaseType.td.json, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2894
```
[ ] Yes
[ ] No
```
=> searchParties has been set to unordered

build.gradle
https://tools.hmcts.net/jira/browse/CCD-2909
bump up spring fw version
```
[ ] Yes
[X] No
```
=> bump up spring fw version

dependency-check-suppressions.xml
There are dependency check issues with elasticsearch-7.16.2.jar, pipeline is failing.This is a suppression change.
```
[ ] Yes
[ x] No
```
=> Elasticsearch-7.16.2.jar suppression

dependency-check-suppressions.xml
Suppresion for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[ x] No
```
=> Spring-core-5.3.18.jar dependency issue suppression

build.gradle, commons/build.gradle, dependency-check-suppressions.xml, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/JsonUtils.java, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/JsonUtilsTest.java
https://tools.hmcts.net/jira/browse/CCD-2574
```
[ ] Yes
[X] No
```
=> jackson.version update for CVE-2020-36518

aat/src/aat/resources/features/F-101 INJECTED_DATA/F-101.feature, aat/src/aat/resources/features/F-101 INJECTED_DATA/S-101.2.td.json, build.gradle, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/AbstractShowConditionValidator.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEnablingConditionValidator.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEnablingConditionValidatorTest.java
https://tools.hmcts.net/jira/browse/CCD-2779
Update validators to allow InjectedData in EventEnablingCondition column of CaseEvent tab
```
[ ] Yes
[X] No
```
=> CCD-2779 - Update validators to allow InjectedData in CaseEvent tab

aat/src/aat/resources/features/F-101 INJECTED_DATA/F-101.feature, aat/src/aat/resources/features/F-101 INJECTED_DATA/S-101.2.td.json, build.gradle, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/AbstractShowConditionValidator.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEnablingConditionValidator.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/validation/event/EventEntityEnablingConditionValidatorTest.java
Reverts hmcts/ccd-definition-store-api#1215
=> Revert "Revert "CCD-2779 - Update validators to allow InjectedData in CaseEvent tab""

aat/src/aat/resources/features/F-102 - TTL Base Complex Type/S-102.2.td.json, build.gradle, dependency-check-suppressions.xml, elastic-search-support/build.gradle
https://tools.hmcts.net/jira/browse/CCD-3150
```
[ ] Yes
[x] No
```
=> package update for CVE-2022-25647

application/src/main/resources/application.properties, charts/ccd-definition-store-api/values.yaml, dependency-check-suppressions.xml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/ApplicationParams.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImpl.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/service/ImportServiceImplTest.java
=> Make welsh translation toggleable

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/excel/SpreadSheetImportTest.java, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/workbasket/WorkBasketUserDefaultService.java, excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/RestResponseEntityExceptionHandler.java, excel-importer/src/test/java/uk/gov/hmcts/ccd/definition/store/excel/endpoint/exception/RestResponseEntityExceptionHandlerTest.java
https://tools.hmcts.net/jira/browse/CCD-2892
```
[ ] Yes
[X] No
```
=> error handling for http 401 status code

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3251
Update suppression for false positive
```
[ ] Yes
[ x] No
```
=> CVE-2016-1000027 is noted as false positive

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3290
Removed suppressions and upgraded spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```
=> Removed suppressions and upgraded spring-framework.version to 5.3.20

charts/ccd-definition-store-api/values.preview.template.yaml
[RDM-13140](https://tools.hmcts.net/jira/browse/RDM-13140)
Revert temporary override of ES Host used to test RDM-13140
```
[ ] Yes
[x] No
```
=> Revert temporary override of ES Host

charts/ccd-definition-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-3376
AKS is failing in Preview Env - update ccd charts
```
[ ] Yes
[x] No
```
=> CCD-3376 update java chart version

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3387
Remove CVE Suppress Until Date from All Services
```
[ ] Yes
[ x] No
```
=> CCD-3387 Remove CVE Suppress Until Date from All Services

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3429
Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305
```
[ ] Yes
[X] No
```
=> Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3440
CCD-3440: Update dependency-check-suppressions.xml for temporary suppression of CVE-2022-33915
```
[ ] Yes
[X] No
```
=> CCD-3440: Update dependency-check-suppressions.xml for temporary suppression of CVE-2022-33915

application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/BaseTest.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/util/KeyGenerator.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/wiremock/config/WireMockTestConfiguration.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/wiremock/extensions/AbstractDynamicResponseTransformer.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/wiremock/extensions/CustomisedResponseTransformer.java, application/src/test/java/uk/gov/hmcts/net/ccd/definition/store/wiremock/extensions/DynamicOAuthJwkSetResponseTransformer.java, application/src/test/resources/mappings/_idam_default.json, application/src/test/resources/mappings/oauth-jwk-set.json, build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2694
```
[ ] Yes
[ ] No
```
=> Spring security version update to 5.6.1

charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-3434
Update java, postgresql and redis configurations
```
[ ] Yes
[x] No
```
=> CCD-3434 update java, postgresql and redis configurations

build.gradle, dependency-check-suppressions.xml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/legacyvalidation/LegacyCaseTypeValidator.java
https://tools.hmcts.net/jira/browse/CCD-3540
Fixed
```
[ ] Yes
[x] No
```
=> CCD-3540: Fix for CVE-2015-3337 and other related CVEs

build.gradle
https://tools.hmcts.net/jira/browse/CCD-3515
CVE-2022-22976
```
[ ] Yes
[ x] No
```
=> Ccd 3515 CVE 2022 22976

build.gradle
=> Update ccd-test-definitions to 7.19.1

build.gradle, dependency-check-suppressions.xml, domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/legacyvalidation/LegacyCaseTypeValidator.java
https://tools.hmcts.net/jira/browse/CCD-3504
Upgrade to latest java plugin in all the repositories
```
[ ] Yes
[x ] No
```
=> CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12.27

build.gradle, charts/ccd-definition-store-api/values.preview.template.yaml
PR to update tested-definitions version to the latest.
```
[ ] Yes
[X] No
```
=> Update ccd-test-definitions to 7.19.3

charts/ccd-definition-store-api/values.preview.template.yaml
CCD-3612 (https://tools.hmcts.net/jira/browse/CCD-3612)
Changed value of USER_PROFILE_HOST in values.preview.template.yaml; replaced ".service.core-compute-preview.internal" with "-java" in value.
```
[ ] Yes
[x] No
```
=> CCD-3612: Fix preview deployment issues

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[x ] No
```
=> Ccd 3577 cleanup CVE suppressions

Jenkinsfile_nightly
Reverts hmcts/ccd-definition-store-api#1257
=> Revert "CCD-3539-CCD-3574: Stop running Nightly builds on weekends, Removal of FTs"

build.gradle, charts/ccd-definition-store-api/values.preview.template.yaml
[CCD-3853](https://tools.hmcts.net/jira/browse/CCD-3853) _"Intermittent Data Store FT failures in nightly build pipelines"_
Run FTAs against the next `ccd-test-definitions` release, see hmcts/ccd-test-definitions#58.
```
[ ] Yes
[x] No
```
=> CCD-3853 run FTAs against next test definition release

application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java, application/src/main/java/uk/gov/hmcts/ccd/definition/store/security/filters/ExceptionHandlingFilter.java, application/src/test/java/uk/gov/hmcts/ccd/definition/store/security/filters/ExceptionHandlingFilterTest.java
https://tools.hmcts.net/jira/browse/CCD-3746
```
[ ] Yes
[ ] No
```
=> created ExceptionHandlingFilter in Security Filter chain

build.gradle, commons/build.gradle
https://tools.hmcts.net/jira/browse/CCD-4043
Replace fasterxml.jackson release candidate with prod-ready version
```
[ ] Yes
[ x] No
```
=> CCD-4043 Fasterxml Jackson Upgrade

application/build.gradle, build.gradle, dependency-check-suppressions.xml
CCD-4047-Fix-CVE-2022-41946
Upgraded 'org.postgresql' to version: '42.5.1'
```
[ ] Yes
[X] No
```
=> CCD-4047-Fix-CVE-2022-41946

repository/src/main/resources/db/useful-queries/Remove all definitions for a case type older than 3 months, but leaving max version.sql
https://tools.hmcts.net/jira/browse/CCD-4068
CCD-4068: Commented out deletion queries for table noc_config as it no longer exists in the db
```
[ ] Yes
[X] No
```
=> CCD-4068: Removed deletion queries for table noc_config

dependency-check-suppressions.xml
=> Suppress CVEs

build.gradle
[CCD-4177](https://tools.hmcts.net/jira/browse/CCD-4177)
PR to update test-definition and beta-fw versions.
```
[ ] Yes
[x] No
```
=> CCD-4177 Updating test-definition and beta-fw versions

repository/src/main/resources/db/migration/V20230131_4159__CCD-4159_drop_noc_config_table.sql
https://tools.hmcts.net/jira/browse/CCD-4159
Added 'drop_config' if exsists. This table has been dropped in all env except for production
```
[ ] Yes
[X] No
```
=> CCD-4159 : Added drop noc_config to flyway scripts

charts/ccd-definition-store-api/values.yaml
https://tools.hmcts.net/jira/browse/CCD-4316
Enable feed to Translation Service in all environments
```
[ ] Yes
[x] No
```
=> CCD-4316 - Enable Welsh feed by default

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/CCD-4344
```
[ ] Yes
[ ] No
```
=> set nightly pipeline cron to 4am

charts/ccd-definition-store-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
=> CCD-4317 Upgrade base charts

infrastructure/ithc.tfvars
=> CCD-4436: Sacle ITHC d/b

charts/ccd-definition-store-api/values.preview.template.yaml
n/a
(Temporarily) redirect data-store dependency to PR-2255.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> Redirect data-store dependency to PR-2255

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4479
https://tools.hmcts.net/jira/browse/CCD-4509
Fix for [CVE-2023-20861](https://github.com/advisories/GHSA-564r-hj7v-mcr5)
CVE-2023-20860
upgrade Spring Framework version to 5.3.26
```
[ ] Yes
[ ] No
```
=> CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860

repository/src/main/resources/db/migration/V20230510_4515__CCD-4515__AmendFlagDetails.sql
https://tools.hmcts.net/jira/browse/CCD-4515
Modification of FlagDetail Complex Base Type
```
[ ] Yes
[x] No
```
=> CCD-4515- Modify FlagDetail

application/src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/CCD-4774
https://tools.hmcts.net/jira/browse/CCD-4789
Add properties spring.servlet.multipart.max-file-size and spring.servlet.multipart.max-request-size to allow importing large definition files.   See screenshots attached to CCD-4774.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-4774: Error while uploading ccd definitions via admin console in perftest env

README.md, application/src/main/resources/application.properties
https://tools.hmcts.net/jira/browse/CCD-4807
reduced to 5s
```
[ ] Yes
[x] No
```
=> Reduce Hikari connection timeout

.github/renovate.json, Jenkinsfile_CNP, dependency-check-suppressions.xml, repository/src/main/resources/db/migration/V20230920_4820__CCD-4820_Updating_Flags.sql
https://tools.hmcts.net/jira/browse/CCD-4820
CCD team will need to add 2 new fields within the Flags basetype.
```
[ ] Yes
[x] No
```
=> Ccd 4820 xtra fields for flags

Jenkinsfile_CNP, build.gradle, charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.yaml, lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/CCD-4866
Updated build.gradle, fix for appinsight logging
```
[ ] Yes
[X] No
```
=> Fix for appinsights logging

Jenkinsfile_CNP
=> CCD-4953 -- Disable Demo sync

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/state.tf, infrastructure/variables.tf
=> CCD-4953 -- Def-Store PG15/flexi D/B

app-insights/build.gradle, app-insights/src/main/java/uk/gov/hmcts/ccd/definition/store/AppInsights.java, app-insights/src/main/java/uk/gov/hmcts/ccd/definition/store/AppInsightsConfiguration.java, application/src/main/java/uk/gov/hmcts/ccd/definition/store/CaseDataAPIApplication.java, build.gradle
https://tools.hmcts.net/jira/browse/CCD-4866
Config update for appinsight
```
[ ] Yes
[X] No
```
=> CCD-4866 : appinsight config update

repository/src/main/resources/db/migration/V20230724_4590__CCD-4590_CreateCaseQueriesCollection.sql, repository/src/main/resources/db/migration/V20231018_4942__CCD-4942_Amend_CreateCaseQueriesCollection.sql
https://tools.hmcts.net/jira/browse/CCD-4942
```
[ ] Yes
[x] No
```
=> CCD-4942: adding missing fields to case query collections.

excel-importer/src/main/java/uk/gov/hmcts/ccd/definition/store/excel/validation/HiddenFieldsValidator.java
https://tools.hmcts.net/jira/browse/CCD-5006
```
[ ] Yes
[ ] No
```
=> remove the retainHiddenValue check as part of ccd-4983

Jenkinsfile_CNP, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/state.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5014)
Terraform file for upgrading data store to v15 flexible servers
```
[ ] Yes
[x] No
```
=> Adding files for v15 upgrade

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4771
bumped jackson.version, removed suppression
```
[ ] Yes
[X] No
```
=> CCD-4771 : Fix CVE-2023-35116

infrastructure/perftest.tfvars
=> Update performance test configurations

infrastructure/aat.tfvars, infrastructure/prod.tfvars
=> Changing prod gen to Mem optimised

application/src/main/java/uk/gov/hmcts/ccd/definition/store/SecurityConfiguration.java
=> Add testing-support/cleanup-case-type to security whitelist

charts/ccd-definition-store-api/values.aat.template.yaml
Updating AAT template to V15 from V11 
```
[ ] Yes
[x] No
```
=> Updating DB Host reference to V15

repository/src/main/resources/db/migration/V20231123_4925__CCD-4925_Update_roleOnCase_label.sql
https://tools.hmcts.net/jira/browse/CCD-4925
```
[ ] Yes
[ ] No
```
=> update the label of roleOnCase field to 'Role On Case'

Jenkinsfile_CNP, Jenkinsfile_nightly, aat/src/aat/resources/features/F-080/S-080.1.td.json
NA
Set 'env.DEFAULT_COLLECTION_ASSERTION_MODE="UNORDERED"' in Jenkins_CNP
```
[ ] Yes
[X] No
```
=> Fix for master build failure on FT ordering

domain/src/main/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapper.java, domain/src/test/java/uk/gov/hmcts/ccd/definition/store/domain/service/EntityToResponseDTOMapperTest.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/AccessTypeRolesRepository.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/entity/AccessTypeRolesEntity.java, repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/model/AccessTypeRolesField.java, repository/src/main/resources/db/migration/V20231121_18__GA-18_add_access_type_roles_table.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/AccessTypeRolesRepositoryTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [x ] the `keep-helm` label has been added, if the helm release should be persisted after a successful build
https://tools.hmcts.net/jira/browse/GA-18
```
[ ] Yes
[ x] No
```
=> GA-18: Add new access_type_roles table

acb.tpl.yaml
https://tools.hmcts.net/jira/browse/CCD-5045
=> CCD-5045 : Fix acb entries to fix timeout issue

build.gradle
=> GA-2 Update Befta version

charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.yaml
=> Ccd 5339 pi33 helm chart upgrade chart java

infrastructure/perftest.tfvars
=> Update perftest cpu 

infrastructure/prod.tfvars
=> DO NOT MERGE- CHG5016403 - increase cpu in db 

repository/src/main/resources/db/migration/V20240509_4917__CCD-4917_Add_Index.sql
=> Ccd 4917 add index

build.gradle
=> ccd-test-definitions same as ccd-data-store-api

src/test/java/uk/gov/hmcts/ccd/definition/store/SmokeTest.java
NA
Attempt to create dummy smoke test class to fix pipeline
```
[ ] Yes
[ ] No
```
=> Update SmokeTest.java - Attempt to create dummy smoke test class to fix pipeline

Jenkinsfile_CNP
NA
Point def store to a specific branch of jenkins which has an increased timeout of 20mins for smoke test.
```
[ ] Yes
[X] No
```
=> increase smoke test timeout to 20 mins

aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1.td.json, aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json
NA
Fix failing FT
```
[ ] Yes
[X] No
```
=> fix master failing Fts

build.gradle
=> fixing missing citizen data in excel for FT tests

Jenkinsfile_CNP, Jenkinsfile_nightly
https://github.com/hmcts/ccd-definition-store-api/pull/1486/files
fix for non retry able method
```
[ ] Yes
[ ] No
```
=> CCD-5624_fix_new

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5158
Upgrade Tomcat to fix CVE-2023-46589
```
[ ] Yes
[x] No
```
=> CCD-5158 Fix CVE-2023-46589

repository/src/main/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeLiteRepository.java
https://tools.hmcts.net/jira/browse/CCD-5911
```
[ ] Yes
[ ] No
```
=> update findByJurisdictionId native query

repository/src/main/resources/db/migration/V20241003_5510_1__CCD-5510_Create_new_indexes.sql, repository/src/main/resources/db/migration/V20241003_5510_2__CCD-5510_Update_case_field_statistics.sql, repository/src/test/java/uk/gov/hmcts/ccd/definition/store/repository/CaseTypeObjectGraphTest.java
https://tools.hmcts.net/jira/browse/CCD-5910
```
[ ] Yes
[ ] No
```
=> add new indexes

build.gradle
=> CME-109 to use ccd-test-definition version 7.24.0

Jenkinsfile_CNP, charts/ccd-definition-store-api/values.preview.template.yaml
NA
revert config back to dev prs
```
[ ] Yes
[X] No
```
=> revert config back to dev prs

Jenkinsfile_CNP
NA
Test only
```
[ ] Yes
[X] No
```
=> CCD-6078 : Test build

aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1a.td.json, aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json, build.gradle
=> CCD-6078 Investigate FT errors in Master pipeline

aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.1a.td.json, aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/S-110.3.td.json
=> fix ordering of roles[...]

application/src/main/resources/application.properties, charts/ccd-definition-store-api/Chart.yaml, charts/ccd-definition-store-api/values.yaml
https://tools.hmcts.net/jira/browse/CCD-5432
add am_org_role_mapping_service to authorised services
```
[ ] Yes
[ ] No
```
=> CCD-5432 - add am_org_role_mapping_service to authorised services

build.gradle, charts/ccd-definition-store-api/Chart.yaml
=> CCD-5651 - Use latest version for beftaFw and ccd-test-definition

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-313
```
[ ] Yes
[x ] No
```
=> CME-313: Update azurerm

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-481
```
[ ] Yes
[x ] No
```
=> CME-481: Disable sync to ITHC for database monitoring testing

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-481
```
[ ] Yes
[x ] No
```
=> CME-481: Add database monitoring

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6286
CCD-6286-Suppress-CVE-2023-6378
```
[ ] Yes
[X] No
```
=> CCD-6286 :: Suppress-CVE-2023-6378

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6362
```
[ ] Yes
[X] No
```
=> Suppress CVE-2024-52316

aat/src/aat/resources/features/F-080/F-080.feature, aat/src/aat/resources/features/F-110 Retrieve Organisation Profile/F-110.feature
https://tools.hmcts.net/jira/browse/CCD-6078
Reverting ignored fts
```
[ ] Yes
[X] No
```
=> CCD-6078 :: reverted ignored fts

Jenkinsfile_CNP, charts/ccd-definition-store-api/values.preview.template.yaml, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6489
CCD-6489 :: suppress CVE 2024 22259
```
[ ] Yes
[X] No
```
=> CCD-6489 :: suppress CVE 2024 22259

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CME-673
Replaced JitPack with Azure Artifacts and updated Fortify client
```
[ ] Yes
[X] No
```
=> CME-673 Replaced JitPack with Azure Artifacts

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6534
Update dependency-check-suppressions.xml
```
[ ] Yes
[X] No
```
=> CCD-6534 :: Update dependency-check-suppressions.xml

dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6636
Suppressed CVE
```
[ ] Yes
[X] No
```
=> CCD-6636 :: Update suppressions.xml
